name: KEA UGCET Tracker

on:
  workflow_dispatch:

  schedule:
    - cron: "*/30 * * * *"

jobs:
  kea-tracker:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run KEA tracker
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python key_tracker.py

      - name: Save seen updates
        run: |
          git config user.name "KEA Tracker"
          git config user.email "kea-tracker@users.noreply.github.com"

          git add seen_updates.json

          git diff --cached --quiet || git commit -m "Update seen KEA notifications"

          git push